### PR TITLE
Update test-lhz one 8

### PR DESCRIPTION
**Pull request by test-lhz**
delete one 8

### CODE REVIEW

**Comment by liudashao** [comment]
what did you do? little guy

**Comment by test-lhz** [comment]
i delete one 8

**Comment by liudashao** [comment]
you should delete two 8

**Comment by test-lhz** [comment]
ok i know

**Comment by test-lhz** [comment]
i modofied

**Comment by test-lhz** [comment]
?

**Comment by liudashao** [comment]
ok, i know

**Pull request merged**
